// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRYGFhMkYeBzwZvf0RSybukgUkQpKT4oM',
    appId: '1:918933147389:web:ced1858667227c024cf894',
    messagingSenderId: '918933147389',
    projectId: 'study-b0fdf',
    authDomain: 'study-b0fdf.firebaseapp.com',
    storageBucket: 'study-b0fdf.firebasestorage.app',
    measurementId: 'G-ZNHZE8GRT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD5Caah9xeNoNhd18dDPdzZS1sUWR35xY',
    appId: '1:918933147389:android:faff7fe051870c714cf894',
    messagingSenderId: '918933147389',
    projectId: 'study-b0fdf',
    storageBucket: 'study-b0fdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDADIuVapoOlCSxJ7v1JYieROPhXcgFJsY',
    appId: '1:918933147389:ios:11fb8223b01ce6c54cf894',
    messagingSenderId: '918933147389',
    projectId: 'study-b0fdf',
    storageBucket: 'study-b0fdf.firebasestorage.app',
    androidClientId: '918933147389-8km7t6896tdql9t45cs20smt2nea3k6h.apps.googleusercontent.com',
    iosClientId: '918933147389-udijv657gbca2su1l2b7q6ciqbuglpse.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDADIuVapoOlCSxJ7v1JYieROPhXcgFJsY',
    appId: '1:918933147389:ios:11fb8223b01ce6c54cf894',
    messagingSenderId: '918933147389',
    projectId: 'study-b0fdf',
    storageBucket: 'study-b0fdf.firebasestorage.app',
    androidClientId: '918933147389-8km7t6896tdql9t45cs20smt2nea3k6h.apps.googleusercontent.com',
    iosClientId: '918933147389-udijv657gbca2su1l2b7q6ciqbuglpse.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRYGFhMkYeBzwZvf0RSybukgUkQpKT4oM',
    appId: '1:918933147389:web:c986962c4b48de4f4cf894',
    messagingSenderId: '918933147389',
    projectId: 'study-b0fdf',
    authDomain: 'study-b0fdf.firebaseapp.com',
    storageBucket: 'study-b0fdf.firebasestorage.app',
    measurementId: 'G-GMH6RDRXEW',
  );
}
